# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 300)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rampContainer = QtWidgets.QWidget(self.centralwidget)
        self.rampContainer.setObjectName("rampContainer")
        self.rampContainerLayout = QtWidgets.QVBoxLayout(self.rampContainer)
        self.rampContainerLayout.setObjectName("rampContainerLayout")
        self.verticalLayout.addWidget(self.rampContainer)
        self.addRampButton = QtWidgets.QPushButton(self.centralwidget)
        self.addRampButton.setObjectName("addRampButton")
        self.verticalLayout.addWidget(self.addRampButton)
        self.generateXMLButton = QtWidgets.QPushButton(self.centralwidget)
        self.generateXMLButton.setObjectName("generateXMLButton")
        self.verticalLayout.addWidget(self.generateXMLButton)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "QGIS Color Ramp Generator"))
        self.addRampButton.setText(_translate("MainWindow", "Add Ramp"))
        self.generateXMLButton.setText(_translate("MainWindow", "Generate XML"))
